global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'aerospike'
    static_configs:
      - targets: ['aerospike-exporter:9145']
